import puppeteer from 'puppeteer-core';
const SEL='[role="dialog"].paper';
const b=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:'new',args:['--no-sandbox','--hide-scrollbars']});
const p=await b.newPage();
await p.evaluateOnNewDocument(()=>{const isE=u=>typeof u==='string'&&/api\.emailjs\.com/i.test(u);
  const XO=XMLHttpRequest.prototype.open,XS=XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.open=function(m,u,...a){this.__u=u;return XO.call(this,m,u,...a)};
  XMLHttpRequest.prototype.send=function(d){if(isE(this.__u)){setTimeout(()=>this.dispatchEvent(new Event('error')),0);return;}return XS.call(this,d)};
  const F=window.fetch;window.fetch=function(u,o){const url=typeof u==='string'?u:(u&&u.url);
    if(isE(url))return Promise.reject(new Error('blocked'));return F.apply(this,arguments)};});
await p.setViewport({width:1280,height:950});
await p.goto(process.env.TARGET,{waitUntil:'networkidle2',timeout:90000});
await p.evaluate(()=>document.querySelectorAll('.cc-window,.cc-banner').forEach(e=>e.remove()));
await p.evaluate(()=>[...document.querySelectorAll('button')].find(x=>/start with pre-validation/i.test(x.textContent)).click());
await p.waitForSelector(SEL,{timeout:15000});
await p.type('#name','Live Founder',{delay:4});
await p.type('#email','live founder@example.com'.replace(' ',''),{delay:4});
await p.type('#phone','(555) 012 3456',{delay:4});
const step=()=>p.evaluate(S=>{const d=document.querySelector(S);const m=d&&d.innerText.match(/Step\s+(\d+)\s*\/\s*(\d+)/i);return m?+m[1]:null},SEL);
for(let i=0;i<18;i++){const s=await step();if(s===11||s===null)break;
  await p.evaluate(S=>{const d=document.querySelector(S);const x=[...d.querySelectorAll('button')].find(y=>/continue|book my pre-validation/i.test(y.textContent)&&!y.disabled);if(x)x.click()},SEL);
  await new Promise(r=>setTimeout(r,420));
  const rd=await p.$$(`${SEL} [role="radio"]`);if(rd.length){await rd[Math.min(1,rd.length-1)].click();await new Promise(r=>setTimeout(r,230));}}
const cal=await p.evaluate(S=>document.querySelector(S).querySelector('.calendly-inline-widget')?.getAttribute('data-url'),SEL);
console.log('   RAW URL:');
console.log('   ',cal);
const qs=cal.split('?')[1]||'';
console.log('   contains "+" anywhere in query? ', qs.includes('+')?'YES ✗':'no ✓');
console.log('   contains %20?                   ', qs.includes('%20')?'yes ✓':'NO ✗');
const u=new URL(cal);
console.log('   DECODED values (what Calendly should show):');
for(const [k,v] of u.searchParams) console.log(`      ${k.padEnd(6)} = ${JSON.stringify(v)}`);
await b.close();
